version: '3.4'
services:
    php:
        container_name: test-proxy-php
        build: .
        privileged: true
        depends_on:
            - postgres
        networks:
            - network
        volumes:
            - .:/app
            - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

    postgres:
        container_name: test-proxy-postgres
        image: postgres:14
        privileged: true
        networks:
            - network
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "127.0.0.1:${DB_PORT}:5432"
        expose:
            - ${DB_PORT}
        volumes:
            - .data:/var/lib/postgresql

    nginx:
        container_name: test-proxy-nginx
        working_dir: /app
        image: nginx:alpine
        depends_on:
            - php
        volumes:
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
            - .:/app
        ports:
            - "127.0.0.1:${NGINX_PORT}:80"
        networks:
            - network

networks:
    network:
